---
- hosts: localhost
  gather_facts: False
  vars_files: all.yml
  tasks:
    - name: Add host to group [bastion]
      add_host:
        name: "{{ helper_vm.public_ip }}"
        groups: bastion
        ansible_ssh_user: "root"
        ansible_ssh_pass: "{{ helper_vm.rootpassword }}"
        host_key_checking: False
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- hosts: bastion
  gather_facts: False
  vars_files: all.yml
  tasks:
    - name: Set the cache of all the download links
      import_role:
        name: cache

- hosts: bastion
  gather_facts: True
  vars_files: all.yml
  environment:
    PATH: "{{ helper_vm.workdir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Create local automation directory
      file:
        path: "{{ helper_vm.workdir }}"
        state: directory
        mode: '0755'

    - name: Run all the common tasks
      import_role:
        name: common

- hosts: bastion
  gather_facts: False
  vars_files: all.yml
  environment:
    PATH: "{{ helper_vm.workdir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Copy over generated ignition files to webserver
      import_role:
        name: webserver
        tasks_from: copy_ign_files

    - name: Download the installer raw.gz file to webserver
      import_role:
        name: webserver
        tasks_from: download_raw_installer_files

- hosts: bastion
  gather_facts: False
  vars_files: all.yml
  environment:
    PATH: "{{ helper_vm.workdir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ vcenter.admin_username }}"
    GOVC_PASSWORD: "{{ vcenter.admin_password }}"
    GOVC_URL: "https://{{ vcenter.ip }}"
    GOVC_INSECURE: 1
  tasks:
    - name: Run the vmware role to setup vCenter folder
      import_role:
        name: vmware
    - name: Reset the vcenter.vm_power_state to poweredoff
      set_fact:
        vcenter: "{{ vcenter | combine({'vm_power_state': 'poweredoff'}, recursive=True) }}"
    - name: Echo the value of the variable vcenter.vm_power_state
      debug: var=vcenter.vm_power_state
    - name: Run steps specific to DHCP and PXE boot
      import_role:
        name: dhcp_pxe
    - name: Run steps for static ip setup of VMs
      import_role:
        name: static_ips
