---


- hosts: webservers
  gather_facts: False
  vars_files: all.yml
  environment:
    PATH: "{{ helper_vm.workdir }}/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Copy over generated ignition files to webserver
      import_role:
        name: webserver
        tasks_from: copy_ign_files
        
    - name: Download the installer raw.gz file to webserver
      import_role:
        name: webserver
        tasks_from: download_raw_installer_files
