bootstrap_ignition_url: http://{{helper_vm.private_ip}}:8080/ignition/bootstrap.ign
bootstrap_vms:
-   cpu: 8
    disksize: 120
    ipaddr: 192.168.30.202
    macaddr: 00:50:56:a8:1a:b1
    name: mcmbt
    ram: 32768
config:
    base_domain: tivlab.raleigh.ibm.com
    cluster_name: mcm
    fips: false
    provider: vsphere
    pull_secret:
        auths:
            cloud.openshift.com:
                auth: b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2xsaXhpbm4xYmFoeXkzYzlneGVjNHp2bHhvZG01OTVya286NkhNOEswR0oxTDdMNzhYTTBNOVUwU1NFTkxGSERZMjMzT0VUOVVEV1NQVjZPTkdYNE83QVI0Tzc4R1dYMjlBRw==
                email: llixinn@cn.ibm.com
            quay.io:
                auth: b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2xsaXhpbm4xYmFoeXkzYzlneGVjNHp2bHhvZG01OTVya286NkhNOEswR0oxTDdMNzhYTTBNOVUwU1NFTkxGSERZMjMzT0VUOVVEV1NQVjZPTkdYNE83QVI0Tzc4R1dYMjlBRw==
                email: llixinn@cn.ibm.com
            registry.connect.redhat.com:
                auth: NTMwNDkwMTF8dWhjLTFiQWh5eTNjOUdYRWM0WnZMeE9kTTU5NVJrbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJZVGcxTmpJM1kyRm1NV0kwTTJReFlUWm1OR0V4TkdOak5EUTVaRGszWXlKOS5zU0kzMncwS0xJYlh5akZNWW5DZjk4NVk2SU9hN0tDRmgtTENzcnVOemNIcGJGLTVYT2Ewem1NVDVxbW53RlNONC1DTFJPeC1Ba1BtM2JkZ2dBQWFoM3ZLQ0xGLVNMM1hESF94VGxxOXM0RUQwdnk4R3lMMWxRbElUOV8zMmtYUjIwVUg4djhDVWJXRXZteGVmUXFlaGcwVmp2TnhzeE8xdjJZVEpPcWo5ZmgwV1FuTTVmZjBwOW41Y0VTQVA5eFFCc25BSzRLUnU4RERJMU5kUHVJQVRNaGZsS3ItTkI2Q3VPSERPRUZCQzdXcjRoVmxFblBWZVVYS05rNVk1M09WMjhpdndFcmVseDd3ODBKMm1EaFduY3lMM2Fuc0pXRG9oUDlKV2NTcTZUNDdPbFk4M0pZazBYVTVLVXE3MDV2cmp5eXFHUE9veVJqU3VPQWw0ekpGUTNOdTQzdE8teU5YcS00aVZINXExQnp6akYwMzdfSkdyQ3VvT2g1NkY0ampSWDRLX1hYaGhnYk5na1ptR25SWXpyTW42b0lrRGFySncwQ2w1cjBlbXczSThrSmMxME5SNjktdnhWSlpsS25kMUE5UjBzN1dUblZQbEJQUnlSMUxkNkQtdW9IY2htRjRlV0d1RzNJYXBTMHE2TzRZTDJqMkFQY05Ndndlb1ZDU01YMWd6cGo4VXNvSmlHRkl6MHJUcW1pRC1mdG45aEY1Vi15Y1JwWk9xY0M3RmVkWW9ubGVvUnV4bUlUNGJuUkk0Y0VETGpiN1VNRHVTNHRSZDNqYkx0bU4wcnByY2xza3VnNjNuRF9FbDBuQ3k0aERVQkYzU0FwT2FaYXBmMmh1ZnFoNmp1dXEyX0Y0VHdJTmxsWWFFbVlaYTV2V1pMLUdMYmlHMF9IZjB6VQ==
                email: llixinn@cn.ibm.com
            registry.redhat.io:
                auth: NTMwNDkwMTF8dWhjLTFiQWh5eTNjOUdYRWM0WnZMeE9kTTU5NVJrbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJZVGcxTmpJM1kyRm1NV0kwTTJReFlUWm1OR0V4TkdOak5EUTVaRGszWXlKOS5zU0kzMncwS0xJYlh5akZNWW5DZjk4NVk2SU9hN0tDRmgtTENzcnVOemNIcGJGLTVYT2Ewem1NVDVxbW53RlNONC1DTFJPeC1Ba1BtM2JkZ2dBQWFoM3ZLQ0xGLVNMM1hESF94VGxxOXM0RUQwdnk4R3lMMWxRbElUOV8zMmtYUjIwVUg4djhDVWJXRXZteGVmUXFlaGcwVmp2TnhzeE8xdjJZVEpPcWo5ZmgwV1FuTTVmZjBwOW41Y0VTQVA5eFFCc25BSzRLUnU4RERJMU5kUHVJQVRNaGZsS3ItTkI2Q3VPSERPRUZCQzdXcjRoVmxFblBWZVVYS05rNVk1M09WMjhpdndFcmVseDd3ODBKMm1EaFduY3lMM2Fuc0pXRG9oUDlKV2NTcTZUNDdPbFk4M0pZazBYVTVLVXE3MDV2cmp5eXFHUE9veVJqU3VPQWw0ekpGUTNOdTQzdE8teU5YcS00aVZINXExQnp6akYwMzdfSkdyQ3VvT2g1NkY0ampSWDRLX1hYaGhnYk5na1ptR25SWXpyTW42b0lrRGFySncwQ2w1cjBlbXczSThrSmMxME5SNjktdnhWSlpsS25kMUE5UjBzN1dUblZQbEJQUnlSMUxkNkQtdW9IY2htRjRlV0d1RzNJYXBTMHE2TzRZTDJqMkFQY05Ndndlb1ZDU01YMWd6cGo4VXNvSmlHRkl6MHJUcW1pRC1mdG45aEY1Vi15Y1JwWk9xY0M3RmVkWW9ubGVvUnV4bUlUNGJuUkk0Y0VETGpiN1VNRHVTNHRSZDNqYkx0bU4wcnByY2xza3VnNjNuRF9FbDBuQ3k0aERVQkYzU0FwT2FaYXBmMmh1ZnFoNmp1dXEyX0Y0VHdJTmxsWWFFbVlaYTV2V1pMLUdMYmlHMF9IZjB6VQ==
                email: llixinn@cn.ibm.com
download:
    clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.12
    dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.6/4.6.8
    govc: https://github.com/vmware/govmomi/releases/download/v0.24.0/govc_linux_amd64.gz
helper_vm:
    disksize: 500
    hostname: mcminf
    memory_mb: 32768
    num_cpus: 16
    private_ip: 192.168.30.201
    private_nic: ens224
    proxy_env: null
    public_dns1: 9.42.4.252
    public_dns2: 9.42.4.253
    public_dnsdomain: mcm.tivlab.raleigh.ibm.com
    public_gateway: 9.42.12.1
    public_ip: 9.42.13.197
    public_netmask: 255.255.252.0
    public_network: VM Network
    public_nic: ens192
    rootpassword: Ams49test
    template: rh78-inf
    workdir: /root/ocp4-vsphere-automation
master_vms:
-   cpu: 16
    disksize: 120
    ipaddr: 192.168.30.210
    macaddr: 00:50:56:a8:1a:b2
    name: mcmc1
    ram: 32768
-   cpu: 16
    disksize: 120
    ipaddr: 192.168.30.211
    macaddr: 00:50:56:a8:1a:b3
    name: mcmc2
    ram: 32768
-   cpu: 16
    disksize: 120
    ipaddr: 192.168.30.212
    macaddr: 00:50:56:a8:1a:b4
    name: mcmc3
    ram: 32768
ntp:
    custom: false
    ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
proxy:
    cert_content: null
    enabled: false
    http_proxy: http://9.111.141.91:3128/
    https_proxy: http://9.111.141.91:3128/
    no_proxy: '{{ config.cluster_name }}.{{ config.base_domain }}'
registry:
    cert_content: null
    email: user@awesome.org
    enabled: false
    host: registry.{{ config.cluster_name }}.{{ config.base_domain }}
    password: ansible
    port: 5000
    product_release_name: ocp-release
    product_release_version: 4.6.12-x86_64
    product_repo: openshift-release-dev
    registry_image: docker.io/library/registry:2
    repo: ocp4/openshift4
    username: ansible
static_ip:
    gateway: 192.168.30.1
    netmask: 255.255.255.0
    network_interface_name: ens192
storage:
    setup_nfs_sc: true
vcenter:
    admin_password: Ams49test!
    admin_username: Administrator@tivlab.raleigh.ibm.com
    cluster: X3750
    datacenter: RTP
    datastore: v7000e_v1
    folder_absolute_path: /RTP/vm/{{ config.cluster_name }}
    ip: 9.42.13.201
    network: Ben
    resource_pool: ocp-resources
    service_account_password: Ams49test!
    service_account_username: Administrator@tivlab.raleigh.ibm.com
    template_name: rhcos
    vm_power_state: poweredon
worker_vms:
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.220
    macaddr: 00:50:56:a8:1a:b5
    name: mcmw1
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.221
    macaddr: 00:50:56:a8:1a:b6
    name: mcmw2
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.222
    macaddr: 00:50:56:a8:1a:b7
    name: mcmw3
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.223
    macaddr: 00:50:56:a8:1a:b8
    name: mcmw4
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.224
    macaddr: 00:50:56:a8:1a:b9
    name: mcmw5
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.225
    macaddr: 00:50:56:a8:1a:ba
    name: mcmw6
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.226
    macaddr: 00:50:56:a8:1a:bb
    name: mcmw7
    ram: 65536
-   cpu: 32
    disksize: 200
    ipaddr: 192.168.30.227
    macaddr: 00:50:56:a8:1a:bc
    name: mcmw8
    ram: 65536
