bootstrap_ignition_url: http://{{helper_vm.private_ip}}:8080/ignition/bootstrap.ign
bootstrap_vms:
-   cpu: 8
    disksize: 50
    ipaddr: 10.0.2.80
    macaddr: 00:50:56:a1:18:a0
    name: mmlabbt
    ram: 24576
config:
    base_domain: cn.ibm.com
    cluster_name: mmlab
    fips: false
    provider: vsphere
    pull_secret:
        auths:
            cloud.openshift.com:
                auth: b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2xsaXhpbm4xYmFoeXkzYzlneGVjNHp2bHhvZG01OTVya286NkhNOEswR0oxTDdMNzhYTTBNOVUwU1NFTkxGSERZMjMzT0VUOVVEV1NQVjZPTkdYNE83QVI0Tzc4R1dYMjlBRw==
                email: llixinn@cn.ibm.com
            quay.io:
                auth: b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2xsaXhpbm4xYmFoeXkzYzlneGVjNHp2bHhvZG01OTVya286NkhNOEswR0oxTDdMNzhYTTBNOVUwU1NFTkxGSERZMjMzT0VUOVVEV1NQVjZPTkdYNE83QVI0Tzc4R1dYMjlBRw==
                email: llixinn@cn.ibm.com
            registry.connect.redhat.com:
                auth: NTMwNDkwMTF8dWhjLTFiQWh5eTNjOUdYRWM0WnZMeE9kTTU5NVJrbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJZVGcxTmpJM1kyRm1NV0kwTTJReFlUWm1OR0V4TkdOak5EUTVaRGszWXlKOS5zU0kzMncwS0xJYlh5akZNWW5DZjk4NVk2SU9hN0tDRmgtTENzcnVOemNIcGJGLTVYT2Ewem1NVDVxbW53RlNONC1DTFJPeC1Ba1BtM2JkZ2dBQWFoM3ZLQ0xGLVNMM1hESF94VGxxOXM0RUQwdnk4R3lMMWxRbElUOV8zMmtYUjIwVUg4djhDVWJXRXZteGVmUXFlaGcwVmp2TnhzeE8xdjJZVEpPcWo5ZmgwV1FuTTVmZjBwOW41Y0VTQVA5eFFCc25BSzRLUnU4RERJMU5kUHVJQVRNaGZsS3ItTkI2Q3VPSERPRUZCQzdXcjRoVmxFblBWZVVYS05rNVk1M09WMjhpdndFcmVseDd3ODBKMm1EaFduY3lMM2Fuc0pXRG9oUDlKV2NTcTZUNDdPbFk4M0pZazBYVTVLVXE3MDV2cmp5eXFHUE9veVJqU3VPQWw0ekpGUTNOdTQzdE8teU5YcS00aVZINXExQnp6akYwMzdfSkdyQ3VvT2g1NkY0ampSWDRLX1hYaGhnYk5na1ptR25SWXpyTW42b0lrRGFySncwQ2w1cjBlbXczSThrSmMxME5SNjktdnhWSlpsS25kMUE5UjBzN1dUblZQbEJQUnlSMUxkNkQtdW9IY2htRjRlV0d1RzNJYXBTMHE2TzRZTDJqMkFQY05Ndndlb1ZDU01YMWd6cGo4VXNvSmlHRkl6MHJUcW1pRC1mdG45aEY1Vi15Y1JwWk9xY0M3RmVkWW9ubGVvUnV4bUlUNGJuUkk0Y0VETGpiN1VNRHVTNHRSZDNqYkx0bU4wcnByY2xza3VnNjNuRF9FbDBuQ3k0aERVQkYzU0FwT2FaYXBmMmh1ZnFoNmp1dXEyX0Y0VHdJTmxsWWFFbVlaYTV2V1pMLUdMYmlHMF9IZjB6VQ==
                email: llixinn@cn.ibm.com
            registry.redhat.io:
                auth: NTMwNDkwMTF8dWhjLTFiQWh5eTNjOUdYRWM0WnZMeE9kTTU5NVJrbzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJZVGcxTmpJM1kyRm1NV0kwTTJReFlUWm1OR0V4TkdOak5EUTVaRGszWXlKOS5zU0kzMncwS0xJYlh5akZNWW5DZjk4NVk2SU9hN0tDRmgtTENzcnVOemNIcGJGLTVYT2Ewem1NVDVxbW53RlNONC1DTFJPeC1Ba1BtM2JkZ2dBQWFoM3ZLQ0xGLVNMM1hESF94VGxxOXM0RUQwdnk4R3lMMWxRbElUOV8zMmtYUjIwVUg4djhDVWJXRXZteGVmUXFlaGcwVmp2TnhzeE8xdjJZVEpPcWo5ZmgwV1FuTTVmZjBwOW41Y0VTQVA5eFFCc25BSzRLUnU4RERJMU5kUHVJQVRNaGZsS3ItTkI2Q3VPSERPRUZCQzdXcjRoVmxFblBWZVVYS05rNVk1M09WMjhpdndFcmVseDd3ODBKMm1EaFduY3lMM2Fuc0pXRG9oUDlKV2NTcTZUNDdPbFk4M0pZazBYVTVLVXE3MDV2cmp5eXFHUE9veVJqU3VPQWw0ekpGUTNOdTQzdE8teU5YcS00aVZINXExQnp6akYwMzdfSkdyQ3VvT2g1NkY0ampSWDRLX1hYaGhnYk5na1ptR25SWXpyTW42b0lrRGFySncwQ2w1cjBlbXczSThrSmMxME5SNjktdnhWSlpsS25kMUE5UjBzN1dUblZQbEJQUnlSMUxkNkQtdW9IY2htRjRlV0d1RzNJYXBTMHE2TzRZTDJqMkFQY05Ndndlb1ZDU01YMWd6cGo4VXNvSmlHRkl6MHJUcW1pRC1mdG45aEY1Vi15Y1JwWk9xY0M3RmVkWW9ubGVvUnV4bUlUNGJuUkk0Y0VETGpiN1VNRHVTNHRSZDNqYkx0bU4wcnByY2xza3VnNjNuRF9FbDBuQ3k0aERVQkYzU0FwT2FaYXBmMmh1ZnFoNmp1dXEyX0Y0VHdJTmxsWWFFbVlaYTV2V1pMLUdMYmlHMF9IZjB6VQ==
                email: llixinn@cn.ibm.com
download:
    clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.7
    dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.6/4.6.1
    govc: https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz
helper_vm:
    disksize: 500
    hostname: mminf
    memory_mb: 16384
    num_cpus: 8
    private_ip: 10.0.2.118
    private_nic: ens224
    proxy_env: http://xcoc-proxy.fyre.ibm.com:3128/
    public_dns1: 9.0.146.50
    public_dns2: 9.42.4.252
    public_dnsdomain: cn.ibm.com
    public_gateway: 9.112.238.1
    public_ip: 9.112.238.118
    public_netmask: 255.255.255.0
    public_network: VM Network
    public_nic: ens192
    rootpassword: Dem0@ring
    template: rh79-01
    workdir: /root/ocp4-vsphere-automation
master_vms:
-   cpu: 8
    disksize: 50
    ipaddr: 10.0.2.81
    macaddr: 00:50:56:a1:18:a1
    name: mmlabc1
    ram: 24576
-   cpu: 8
    disksize: 50
    ipaddr: 10.0.2.82
    macaddr: 00:50:56:a1:18:a2
    name: mmlabc2
    ram: 24576
-   cpu: 8
    disksize: 50
    ipaddr: 10.0.2.83
    macaddr: 00:50:56:a1:18:a3
    name: mmlabc3
    ram: 24576
ntp:
    custom: false
    ntp_server_list:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
proxy:
    cert_content: null
    enabled: false
    http_proxy: http://9.111.141.91:3128/
    https_proxy: http://9.111.141.91:3128/
    no_proxy: '{{ config.cluster_name }}.{{ config.base_domain }}'
registry:
    cert_content: null
    email: user@awesome.org
    enabled: false
    host: registry.{{ config.cluster_name }}.{{ config.base_domain }}
    password: ansible
    port: 5000
    product_release_name: ocp-release
    product_release_version: 4.6.6-x86_64
    product_repo: openshift-release-dev
    registry_image: docker.io/library/registry:2
    repo: ocp4/openshift4
    username: ansible
static_ip:
    gateway: 10.0.2.254
    netmask: 255.255.255.0
    network_interface_name: ens192
storage:
    setup_nfs_sc: true
vcenter:
    admin_password: Dem0@18m
    admin_username: Administrator@mmlab.cn.ibm.com
    cluster: cluster0
    datacenter: Datacenter
    datastore: ds_demo01
    folder_absolute_path: /Datacenter/vm/{{ config.cluster_name }}
    ip: 9.112.238.90
    network: DPortGroup
    resource_pool: demopool
    service_account_password: Dem0@18m
    service_account_username: Administrator@mmlab.cn.ibm.com
    template_name: rhcos-vmware
    vm_power_state: poweredon
worker_vms:
-   cpu: 8
    disksize: 100
    ipaddr: 10.0.2.84
    macaddr: 00:50:56:a1:18:a4
    name: mmlabw1
    ram: 32768
-   cpu: 8
    disksize: 100
    ipaddr: 10.0.2.85
    macaddr: 00:50:56:a1:18:a5
    name: mmlabw2
    ram: 32768
-   cpu: 8
    disksize: 100
    ipaddr: 10.0.2.86
    macaddr: 00:50:56:a1:18:a6
    name: mmlabw3
    ram: 32768
-   cpu: 8
    disksize: 100
    ipaddr: 10.0.2.87
    macaddr: 00:50:56:a1:18:a7
    name: mmlabw4
    ram: 32768
-   cpu: 8
    disksize: 100
    ipaddr: 10.0.2.88
    macaddr: 00:50:56:a1:18:a8
    name: mmlabw5
    ram: 32768
-   cpu: 8
    disksize: 100
    ipaddr: 10.0.2.89
    macaddr: 00:50:56:a1:18:a9
    name: mmlabw6
    ram: 32768
