---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Generate var file to landing extra vars
      copy:
        content: "{{ ocpconfig | to_nice_yaml }}"
        dest: "current_ocpconfig.yml"
    - name: Loading current ocpconfig var file
      include_vars: current_ocpconfig.yml

    - name: Prepare helper vars-static var file
      template:
        src: vars-static.j2
        dest: "{{ playbook_dir }}/vars-static.yml"
        mode: 0644
        force: yes
    - name: Create VM for bastion host
      import_role:
        name: bastion
        tasks_from: create_vm_bastion

    - name: Add host to group [bastion]
      add_host:
        name: "{{ helper_vm.public_ip }}"
        groups: bastion
        ansible_ssh_user: "root"
        ansible_ssh_pass: "{{ helper_vm.rootpassword }}"
        host_key_checking: False
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: Add host to group [webservers]
      add_host:
        name: "{{ helper_vm.public_ip }}"
        groups: webservers
        ansible_ssh_user: "root"
        ansible_ssh_pass: "{{ helper_vm.rootpassword }}"
        host_key_checking: False
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- hosts: bastion
  gather_facts: True
  vars_files:
    - roles/helper/vars/main.yml
  environment:
    PATH: "{{ ocpconfig.helper_vm.workdir }}/bin:{{ ansible_env.PATH }}"
    GOVC_USERNAME: "{{ ocpconfig.vcenter.admin_username }}"
    GOVC_PASSWORD: "{{ ocpconfig.vcenter.admin_password }}"
    GOVC_URL: "https://{{ ocpconfig.vcenter.ip }}"
    GOVC_INSECURE: 1
  handlers:
  - import_tasks: roles/helper/handlers/main.yml
  tasks:
    - name: Loading current ocpconfig var file to bastion node
      include_vars: current_ocpconfig.yml
    - name: include vars-static
      include_vars: vars-static.yml
    - name: validate hostnames
      import_tasks: roles/helper/tasks/validate_host_names.yaml

    - name: Get current openshift-install minor version
      shell: "{{ helper_vm.workdir }}/bin/openshift-install version|head -n 1|awk '{print $2}'|cut -f2 -d'.'"
      register: ocp_minor_version

    - debug:
        msg: "{{ ocp_minor_version.stdout }}"

    - name: Remove manifest files for control plane machines and compute machineSets (UPI)
      shell: "rm -f {{ helper_vm.workdir }}/install-dir/openshift/99_openshift-cluster-api_master-machines-*.yaml {{ helper_vm.workdir }}/install-dir/openshift/99_openshift-cluster-api_worker-machineset-*.yaml"
      when:
        - ocp_minor_version.stdout|int > 4
