apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-storage-provisioner
  resources:
    requests:
      storage: 100Gi
