    - name: Fetch the install-config.yaml for facts setting
      fetch:
        src: "{{ helper_vm.workdir }}/install-dir/install-config.yaml"
        dest: "{{ playbook_dir }}/{{ inventory_hostname }}_install-config.yaml"
        flat: yes

    - name: Create a dictionary out of the install-config.yaml file
      include_vars:
        file: '{{ playbook_dir }}/{{ inventory_hostname }}_install-config.yaml'
        name: install_config

    - name: Add a additionalTrustBundle element to the install_config dict
      set_fact:
        install_config: "{{ install_config | combine({'additionalTrustBundle': proxy.cert_content}, recursive=True)}}"
      when:  proxy.cert_content is defined and proxy.cert_content | type_debug != "NoneType" and proxy.cert_content | length > 0

    - name: Convert the install_config dict back into YAML for installation
      copy:
        content: "{{ install_config | to_nice_yaml }}"
        dest: "{{ helper_vm.workdir }}/install-dir/install-config.yaml"
