    - name: Generate the ignition manifests
      command: "openshift-install create manifests --dir={{ helper_vm.workdir }}/install-dir"

    - name: Get current openshift-install minor version
      shell: "{{ helper_vm.workdir }}/bin/openshift-install version|head -n 1|awk '{print $2}'|cut -f2 -d'.'"
      register: ocp_minor_version

    - name: Remove manifest files for control plane machines and compute machineSets (UPI)
      shell: "rm -f {{ helper_vm.workdir }}/install-dir/openshift/99_openshift-cluster-api_master-machines-*.yaml {{ helper_vm.workdir }}/install-dir/openshift/99_openshift-cluster-api_worker-machineset-*.yaml"
      when:
        - ocp_minor_version.stdout|int > 4

#    - name: Remove hash value for vsphere vm folder definition (UPI)
#      replace:
#        dest: "{{ helper_vm.workdir }}/install-dir/manifest/cloud-provider-config.yaml"
#        regexp: >-
#          (folder\s=).*$
#        replace: >-
#          \1 "{{ folder_absolute_path}}"
#      when: vcenter.folder_absolute_path is defined and ocp_minor_version.stdout|int > 4

# -------------------------------------------------------------
    - name: Get current openshift-install infrastructureName hash value
      shell: "cat {{ helper_vm.workdir }}/install-dir/manifests/cluster-infrastructure-02-config.yml|grep infrastructureName|awk '{print $2}'"
      register: ocp_infrastructureName_hash
      when:
          - ocp_minor_version.stdout|int > 4

    - name: Update VM folder for new hash value
      command: "govc object.rename {{ vcenter.folder_absolute_path }} {{ ocp_infrastructureName_hash.stdout}}"
      when:
          - ocp_minor_version.stdout|int > 4

    - name: Update the vcenter.folder_absolute_path for new hash
      set_fact:
        vcenter: "{{ vcenter | combine({'folder_absolute_path': '/'+datacenter+'/vm/'+ocp_infrastructureName_hash.stdout}, recursive=True) }}"
      when: vcenter.folder_absolute_path is defined and ocp_minor_version.stdout|int > 4

    - name: Display the new absolute folder path of the vCenter folder
      debug:
        var: vcenter.folder_absolute_path
        verbosity: 1

# -------------------------------------------------------------


    - name: Apply the patch to set mastersSchedulable to false
      patch:
        src: "cluster-scheduler-02-config.yml.patch"
        dest: "{{ helper_vm.workdir }}/install-dir/manifests/cluster-scheduler-02-config.yml"

    - name: Configure custom ntp servers for masters and workers
      when: ntp.custom
      include_tasks: configure_ntp.yml

    - name: Generate the ignition configs
      command: "openshift-install create ignition-configs --dir={{ helper_vm.workdir }}/install-dir"
