  - name: Run all the pre-install steps
    include: pre_install.yml

  - name: Run the setup tasks for a restricted environment
    when: registry.enabled
    include: setup_registry.yml

  - name: Run the tasks for a restricted environment
    when: registry.enabled
    include: utilize_registry.yml

  - name: Run all the install steps
    include: install.yml
