  - name: Create bootstrap VM from the template
    vmware_guest:
      hostname: "{{ vcenter.ip }}"
      username: "{{ vcenter.service_account_username }}"
      password: "{{ vcenter.service_account_password }}"
      datacenter: "{{ vcenter.datacenter }}"
      cluster: "{{ vcenter.cluster}}"
      resource_pool: "{{ vcenter.resource_pool }}"
      guest_id: "rhel7_64Guest"
      validate_certs: no
      folder: "{{ vcenter.folder_absolute_path }}"
      name: "{{ item.name }}"
      state: "{{ vcenter.vm_power_state }}"
      disk:
      - size_gb: "{{ hwconfig.bootstrap.size_gb }}"
        type: None
        datastore: "{{ vcenter.datastore }}"
      hardware:
        memory_mb: "{{ hwconfig.bootstrap.memory_mb }}"
        num_cpus: "{{ hwconfig.bootstrap.num_cpus }}"
        memory_reservation_lock: True
      networks:
      - name: "{{ vcenter.network }}"
        mac: "{{ item.macaddr }}"
      wait_for_ip_address: no
    loop: "{{ bootstrap_vms }}"
  - name: Create master VMs from the template
    vmware_guest:
      hostname: "{{ vcenter.ip }}"
      username: "{{ vcenter.service_account_username }}"
      password: "{{ vcenter.service_account_password }}"
      datacenter: "{{ vcenter.datacenter }}"
      cluster: "{{ vcenter.cluster}}"
      resource_pool: "{{ vcenter.resource_pool }}"
      guest_id: "rhel7_64Guest"
      validate_certs: no
      folder: "{{ vcenter.folder_absolute_path }}"
      name: "{{ item.name }}"
      state: "{{ vcenter.vm_power_state }}"
      disk:
      - size_gb: "{{ hwconfig.master.size_gb }}"
        type: None
        datastore: "{{ vcenter.datastore }}"
      hardware:
        memory_mb: "{{ hwconfig.master.memory_mb }}"
        num_cpus: "{{ hwconfig.master.num_cpus }}"
        memory_reservation_lock: True
      networks:
      - name: "{{ vcenter.network }}"
        mac: "{{ item.macaddr }}"
      wait_for_ip_address: no
    loop: "{{ master_vms }}"

  - name: Create worker VMs from the template
    vmware_guest:
      hostname: "{{ vcenter.ip }}"
      username: "{{ vcenter.service_account_username }}"
      password: "{{ vcenter.service_account_password }}"
      datacenter: "{{ vcenter.datacenter }}"
      cluster: "{{ vcenter.cluster}}"
      resource_pool: "{{ vcenter.resource_pool }}"
      guest_id: "rhel7_64Guest"
      validate_certs: no
      folder: "{{ vcenter.folder_absolute_path }}"
      name: "{{ item.name }}"
      state: "{{ vcenter.vm_power_state }}"
      disk:
      - size_gb: "{{ hwconfig.worker.size_gb }}"
        type: None
        datastore: "{{ vcenter.datastore }}"
      hardware:
        memory_mb: "{{ hwconfig.worker.memory_mb }}"
        num_cpus: "{{ hwconfig.worker.num_cpus }}"
        memory_reservation_lock: True
      networks:
      - name: "{{ vcenter.network }}"
        mac: "{{ item.macaddr }}"
      wait_for_ip_address: no
    loop: "{{ worker_vms }}"

  - name: Update VM options on the template
    command: "govc vm.change -vm {{ vcenter.folder_absolute_path }}/{{ item.name }} -e=disk.EnableUUID=TRUE"
    loop: "{{ bootstrap_vms + master_vms + worker_vms }}"
